[tool.poetry]
name = "testproject"
version = "0.1.0"
description = ""
authors = ["pavlentiod <levap.spb@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
alembic = "^1.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
